// Copyright (C) 2021 Storj Labs, Inc.
// See LICENSE for copying information.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: clickfarmer.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ClickCounts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Red   int64 `protobuf:"varint,1,opt,name=red,proto3" json:"red,omitempty"`
	Green int64 `protobuf:"varint,2,opt,name=green,proto3" json:"green,omitempty"`
	Blue  int64 `protobuf:"varint,3,opt,name=blue,proto3" json:"blue,omitempty"`
}

func (x *ClickCounts) Reset() {
	*x = ClickCounts{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clickfarmer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClickCounts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClickCounts) ProtoMessage() {}

func (x *ClickCounts) ProtoReflect() protoreflect.Message {
	mi := &file_clickfarmer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClickCounts.ProtoReflect.Descriptor instead.
func (*ClickCounts) Descriptor() ([]byte, []int) {
	return file_clickfarmer_proto_rawDescGZIP(), []int{0}
}

func (x *ClickCounts) GetRed() int64 {
	if x != nil {
		return x.Red
	}
	return 0
}

func (x *ClickCounts) GetGreen() int64 {
	if x != nil {
		return x.Green
	}
	return 0
}

func (x *ClickCounts) GetBlue() int64 {
	if x != nil {
		return x.Blue
	}
	return 0
}

type GetClicksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetClicksRequest) Reset() {
	*x = GetClicksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clickfarmer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetClicksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClicksRequest) ProtoMessage() {}

func (x *GetClicksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clickfarmer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClicksRequest.ProtoReflect.Descriptor instead.
func (*GetClicksRequest) Descriptor() ([]byte, []int) {
	return file_clickfarmer_proto_rawDescGZIP(), []int{1}
}

type GetClicksResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClickCounts *ClickCounts `protobuf:"bytes,1,opt,name=clickCounts,proto3" json:"clickCounts,omitempty"`
}

func (x *GetClicksResponse) Reset() {
	*x = GetClicksResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clickfarmer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetClicksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClicksResponse) ProtoMessage() {}

func (x *GetClicksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clickfarmer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClicksResponse.ProtoReflect.Descriptor instead.
func (*GetClicksResponse) Descriptor() ([]byte, []int) {
	return file_clickfarmer_proto_rawDescGZIP(), []int{2}
}

func (x *GetClicksResponse) GetClickCounts() *ClickCounts {
	if x != nil {
		return x.ClickCounts
	}
	return nil
}

type SetClicksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClickCounts *ClickCounts `protobuf:"bytes,1,opt,name=clickCounts,proto3" json:"clickCounts,omitempty"`
}

func (x *SetClicksRequest) Reset() {
	*x = SetClicksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clickfarmer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetClicksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetClicksRequest) ProtoMessage() {}

func (x *SetClicksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clickfarmer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetClicksRequest.ProtoReflect.Descriptor instead.
func (*SetClicksRequest) Descriptor() ([]byte, []int) {
	return file_clickfarmer_proto_rawDescGZIP(), []int{3}
}

func (x *SetClicksRequest) GetClickCounts() *ClickCounts {
	if x != nil {
		return x.ClickCounts
	}
	return nil
}

type SetClicksResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetClicksResponse) Reset() {
	*x = SetClicksResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clickfarmer_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetClicksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetClicksResponse) ProtoMessage() {}

func (x *SetClicksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clickfarmer_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetClicksResponse.ProtoReflect.Descriptor instead.
func (*SetClicksResponse) Descriptor() ([]byte, []int) {
	return file_clickfarmer_proto_rawDescGZIP(), []int{4}
}

var File_clickfarmer_proto protoreflect.FileDescriptor

var file_clickfarmer_proto_rawDesc = []byte{
	0x0a, 0x11, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x66, 0x61, 0x72, 0x6d, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x66, 0x61, 0x72, 0x6d, 0x65, 0x72,
	0x22, 0x49, 0x0a, 0x0b, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x12,
	0x10, 0x0a, 0x03, 0x72, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x72, 0x65,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x65, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x67, 0x72, 0x65, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6c, 0x75, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x62, 0x6c, 0x75, 0x65, 0x22, 0x12, 0x0a, 0x10, 0x47,
	0x65, 0x74, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x4f, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x0b, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63, 0x6c, 0x69, 0x63,
	0x6b, 0x66, 0x61, 0x72, 0x6d, 0x65, 0x72, 0x2e, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x73, 0x52, 0x0b, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x73,
	0x22, 0x4e, 0x0a, 0x10, 0x53, 0x65, 0x74, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x3a, 0x0a, 0x0b, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63, 0x6c, 0x69, 0x63,
	0x6b, 0x66, 0x61, 0x72, 0x6d, 0x65, 0x72, 0x2e, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x73, 0x52, 0x0b, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x73,
	0x22, 0x13, 0x0a, 0x11, 0x53, 0x65, 0x74, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xa9, 0x01, 0x0a, 0x0b, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x46,
	0x61, 0x72, 0x6d, 0x65, 0x72, 0x12, 0x4c, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x69, 0x63,
	0x6b, 0x73, 0x12, 0x1d, 0x2e, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x66, 0x61, 0x72, 0x6d, 0x65, 0x72,
	0x2e, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1e, 0x2e, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x66, 0x61, 0x72, 0x6d, 0x65, 0x72, 0x2e,
	0x47, 0x65, 0x74, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x4c, 0x0a, 0x09, 0x53, 0x65, 0x74, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x73,
	0x12, 0x1d, 0x2e, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x66, 0x61, 0x72, 0x6d, 0x65, 0x72, 0x2e, 0x53,
	0x65, 0x74, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1e, 0x2e, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x66, 0x61, 0x72, 0x6d, 0x65, 0x72, 0x2e, 0x53, 0x65,
	0x74, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_clickfarmer_proto_rawDescOnce sync.Once
	file_clickfarmer_proto_rawDescData = file_clickfarmer_proto_rawDesc
)

func file_clickfarmer_proto_rawDescGZIP() []byte {
	file_clickfarmer_proto_rawDescOnce.Do(func() {
		file_clickfarmer_proto_rawDescData = protoimpl.X.CompressGZIP(file_clickfarmer_proto_rawDescData)
	})
	return file_clickfarmer_proto_rawDescData
}

var file_clickfarmer_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_clickfarmer_proto_goTypes = []interface{}{
	(*ClickCounts)(nil),       // 0: clickfarmer.ClickCounts
	(*GetClicksRequest)(nil),  // 1: clickfarmer.GetClicksRequest
	(*GetClicksResponse)(nil), // 2: clickfarmer.GetClicksResponse
	(*SetClicksRequest)(nil),  // 3: clickfarmer.SetClicksRequest
	(*SetClicksResponse)(nil), // 4: clickfarmer.SetClicksResponse
}
var file_clickfarmer_proto_depIdxs = []int32{
	0, // 0: clickfarmer.GetClicksResponse.clickCounts:type_name -> clickfarmer.ClickCounts
	0, // 1: clickfarmer.SetClicksRequest.clickCounts:type_name -> clickfarmer.ClickCounts
	1, // 2: clickfarmer.ClickFarmer.GetClicks:input_type -> clickfarmer.GetClicksRequest
	3, // 3: clickfarmer.ClickFarmer.SetClicks:input_type -> clickfarmer.SetClicksRequest
	2, // 4: clickfarmer.ClickFarmer.GetClicks:output_type -> clickfarmer.GetClicksResponse
	4, // 5: clickfarmer.ClickFarmer.SetClicks:output_type -> clickfarmer.SetClicksResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_clickfarmer_proto_init() }
func file_clickfarmer_proto_init() {
	if File_clickfarmer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_clickfarmer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClickCounts); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clickfarmer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetClicksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clickfarmer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetClicksResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clickfarmer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetClicksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clickfarmer_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetClicksResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_clickfarmer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clickfarmer_proto_goTypes,
		DependencyIndexes: file_clickfarmer_proto_depIdxs,
		MessageInfos:      file_clickfarmer_proto_msgTypes,
	}.Build()
	File_clickfarmer_proto = out.File
	file_clickfarmer_proto_rawDesc = nil
	file_clickfarmer_proto_goTypes = nil
	file_clickfarmer_proto_depIdxs = nil
}
